language: go
go:
  - 1.10.x
  - 1.9.x
  - 1.8.x
install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure
  - docker-compose -f testdata/docker-compose.yml up -d
script:
  - make default test-race
services:
  - docker
